import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff', padding: 20},
  container: {flex: 1, backgroundColor: '#fff', padding: 20},
  header: {flexDirection: 'row', justifyContent: 'space-between'},
  title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 0},
  topSection: {
    width: '100%',
    height: 95,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  homeImage: {width: 70, height: 80},
  storeTitle: {
    fontSize: 18,
    color: '#000',
    fontWeight: '400',
    textAlign: 'left',
  },
  StoreAdd: {fontSize: 14, color: '#979797', fontWeight: '400'},
  storeContact: {flexDirection: 'row', justifyContent: 'space-between'},
  visitDate: {fontSize: 12, fontWeight: '400', color: '#00CFE8'},
  visitDay: {fontSize: 12, fontWeight: '400', color: '#FF0000'},
  visitNo: {
    fontSize: 40,
    fontWeight: '400',
    color: '#00CFE8',
    textAlign: 'center',
  },
  visitText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#00CFE8',
    textAlign: 'center',
  },

  KRP: {
    fontSize: 14,
    fontWeight: '400',
    color: '#4B4B4B',
    paddingLeft: 20,
    marginTop: 15,
  },
  editCon: {
    width: '100%',
    height: 390,
    borderWidth: 1,
    marginTop: 25,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#0000',
    elevation: 5,
    borderColor: 'rgba(0, 0, 0, 0.25)',
    overflow: 'hidden',
  },
  editSec: {
    width: '100%',
    height: 40,
    borderColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#0000',
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 6,
  },
  edit: {fontSize: 18, fontWeight: '400', color: '#000'},
  boxContainer: {
    width: '100%',
    flexDirection: 'row',
  },
  image: {width: '20%', padding: 8},
  productDesc: {width: '80%', padding: 20},
  productTitle: {fontSize: 18, fontWeight: '400', color: '#000'},
  quantityDesc: {flexDirection: 'row', justifyContent: 'space-between'},
  quantity: {color: '#00CFE8', fontSize: 16, fontWeight: '400'},
  priceDesc: {flexDirection: 'row', justifyContent: 'space-between'},
  price: {color: '#000', fontSize: 20, fontWeight: '400'},
  btn: {
    width: '40%',
    height: 40,
    backgroundColor: '#00CFE8',
    marginTop: 30,
    alignSelf: 'center',
    borderRadius: 10,
    marginBottom: 20,
  },
  btnText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginTop: 5,
  },
  line: {borderBottomWidth: 1, borderColor: '#BABFC7', paddingBottom: 10},
  heading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    left: 10,
  },
  firstTitle: {fontSize: 12, fontWeight: '600'},
  compulsory: {color: '#EA5455'},
  dropDownMenuFull: {
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
  },
  productDetails: {flexDirection: 'row', justifyContent: 'space-between'},
});
