import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {backgroundColor: '#fff', flex: 1, padding: 20},
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  headerImage: {marginTop: 10},
  title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 15},
  borderStyle: {
    width: '100%',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    paddingLeft: 10,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 5,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 3,
  },
  btn: {
    width: '100%',
    height: 60,
    backgroundColor: '#00CFE8',
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 10,
  },
  inputText: {fontSize: 14},
  topLabelText: {fontSize: 12, position: 'absolute', top: -1, color: '#A9A7A7'},
  dropDown: {flexDirection: 'row', justifyContent: 'space-between'},
  dropDownMenu: {
    width: '49%',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
  },
  heading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    left: 10,
    top: 0,
  },
  firstTitle: {fontSize: 12, fontWeight: '600'},
  compulsory: {color: '#EA5455'},
  dropDownMenuFull: {
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
  },
  checkBox: {fontSize: 14, fontWeight: '400', color: '#000', marginTop: 8},
  checkbox: {flexDirection: 'row', marginTop: 15},
  textInputStyle: {marginTop: 10, width: '100%'},
});
