import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff', padding: 20},
  header: {flexDirection: 'row', justifyContent: 'space-between'},

  topSection: {
    width: '100%',
    height: 95,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
   
   
  },
  homeImage: {width:70, height:80,alignSelf:"center"},
  storeTitle: {
    fontSize: 18,
    color: '#000',
    fontWeight: '400',
    textAlign: 'left',
  },
  StoreAdd: {fontSize: 14, color: '#979797', fontWeight: '400'},
  storeContact: {flexDirection: 'row', justifyContent: 'space-between'},
  visitDate: {fontSize: 12, fontWeight: '400', color: '#00CFE8'},
  visitDay: {fontSize: 12, fontWeight: '400', color: '#FF0000'},
  visitNo: {fontSize: 40, fontWeight: '400', color: '#00CFE8'},
  visitText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#00CFE8',
   
  },
  // horizontal: {flexDirection: 'row', alignItems: 'center', padding: 30},
  // horizontalLine: {flex: 1, height: 1, backgroundColor: '#BABFC7'},
  KRP: {fontSize: 14, fontWeight: '400', color: '#4B4B4B', paddingLeft: 20,marginTop:15},
  date: {height: 45, backgroundColor: '#fff'},
  inputSec: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  uploadBtn: {
    width: '45%',
    height: 45,
    marginTop: 15,
    alignSelf: 'center',
    backgroundColor: '#00CFE8',
    borderRadius: 5,
  },
  upload: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#fff',
    marginTop: 7,
  },
  editCon: {
    width: '100%',
    height: 300,
    borderWidth: 1,
    marginTop: 25,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#0000',
    elevation: 5,
    borderColor: 'rgba(0, 0, 0, 0.25)',
    overflow:'hidden',
  paddingbottom:10
  },
  editSec: {
    width: '100%',
    height: 40,
    borderColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#0000',
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 6,
  },
  edit: {fontSize: 18, fontWeight: '400', color: '#000'},
  boxContainer: {
    width: '100%',
    flexDirection: 'row',
    marginBottom:10
  },
  image: {width: '20%', padding: 8},
  productDesc: {width: '80%', padding: 20},
  productTitle: {fontSize: 18, fontWeight: '400', color: '#000'},
  quantityDesc: {flexDirection: 'row', justifyContent: 'space-between'},
  quantity: {color: '#00CFE8', fontSize: 16, fontWeight: '400'},
  priceDesc: {flexDirection: 'row', justifyContent: 'space-between'},
  price: {color: '#000', fontSize: 20, fontWeight: '400'},
  heading:{flexDirection:"row",justifyContent:"space-between",position:"absolute",left:10,top:-2},
  firstTitle:{fontSize:12,fontWeight:"600"},compulsory:{color:"#EA5455"},
  dropDownMenuFull:{
    borderWidth: 1,
    height: 50,
    // marginTop: 10,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
  },
  line:{ borderBottomWidth:1,
    borderColor:'#BABFC7',paddingBottom:9},
    title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 15},
  borderStyle: {
    width: '49%',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    paddingLeft: 10,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 5,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 3,
  },
  productDetails:{flexDirection:"row",justifyContent:"space-between"},
  title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 0},
  back:{width:38,height:38}
});
