import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {backgroundColor: '#fff', flex: 1, padding: 20},
  header: {flexDirection: 'row', justifyContent: 'space-between'},
  back: {width: 38, height: 38},
  title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 3},
  Header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 22,
  },
  pendingView: {
    width: '40%',
    height: 28,
    backgroundColor: '#00CFE8',
    borderRadius: 15,
  },
  pendingText: {
    color: '#fff',
    textAlign: 'center',
    marginTop: 3,
    fontSize: 14,
    fontWeight: '500',
  },
  allView: {
    width: '40%',
    height: 28,
    borderColor: '#DDDDDD',
    borderRadius: 15,
    borderWidth: 2,
  },
  allText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#000',
    textAlign: 'center',
    marginTop: 3,
  },
  filterImage: {width: 20, height: 20, marginTop: 3},
  textInput: {
    width: '100%',
    height: 40,
    borderWidth: 1,
    marginTop: 20,
    borderRadius: 5,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 4,
    borderColor: 'rgba(0, 0, 0, 0.2)',
  },
  areaSec: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  text: {fontSize: 14, fontWeight: '400', color: '#BABFC7'},
  topSection: {
    width: '100%',
    height: 115,
    marginTop: 26,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#00CFE8',
    shadowColor: '#000',
    elevation: 2,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
  homeImage: {width: 60, height: 60, alignSelf: 'center'},
  storeTitle: {
    fontSize: 18,
    color: '#000',
    fontWeight: '400',
    textAlign: 'left',
  },
  StoreAdd: {fontSize: 14, color: '#979797', fontWeight: '400'},
  storeContact: {flexDirection: 'row', justifyContent: 'space-between'},
  visitDate: {fontSize: 12, fontWeight: '400', color: '#00CFE8'},
  visitDay: {fontSize: 12, fontWeight: '400', color: '#FF0000'},
  visitNo: {
    fontSize: 40,
    fontWeight: '400',
    color: '#00CFE8',
    textAlign: 'center',
  },
  visitText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#00CFE8',
    textAlign: 'center',
  },
  Section: {
    width: '100%',
    height: 125,
    marginTop: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#979797',
    shadowColor: '#000',
    elevation: 2,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
});
