import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff', padding: 20},
  header: {flexDirection: 'row', justifyContent: 'space-between'},
  title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 0},
  Header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 22,
  },
  pendingView: {
    width: '40%',
    height: 28,
    backgroundColor: '#00CFE8',
    borderRadius: 15,
  },
  pendingText: {
    color: '#fff',
    textAlign: 'center',
    marginTop: 3,
    fontSize: 14,
    fontWeight: '500',
  },
  allView: {
    width: '40%',
    height: 28,
    borderColor: '#DDDDDD',
    borderRadius: 15,
    borderWidth: 2,
  },
  allText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#000',
    textAlign: 'center',
    marginTop: 3,
  },
  filterImage: {width: 20, height: 20, marginTop: 3},
  topSection: {
    width: '100%',
    height: 115,
    marginTop: 26,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#00CFE8',
    shadowColor: '#000',
   elevation:2,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  homeImage: {width: 60, height: 60, alignSelf: 'center'},
  storeTitle: {
    fontSize: 18,
    color: '#000',
    fontWeight: '400',
    textAlign: 'left',
  },
  StoreAdd: {fontSize: 14, color: '#979797', fontWeight: '400'},
  storeContact: {flexDirection: 'row', justifyContent: 'space-between'},
  visitDate: {fontSize: 12, fontWeight: '400', color: '#00CFE8'},
  visitDay: {fontSize: 12, fontWeight: '400', color: '#FF0000'},
  visitNo: {
    fontSize: 40,
    fontWeight: '400',
    color: '#00CFE8',
    textAlign: 'center',
  },
  visitText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#00CFE8',
    textAlign: 'center',
  },
  Section: {
    width: '100%',
    height: 115,
    marginTop: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#979797',
    shadowColor: '#000',
    elevation: 2,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  backgroundColor: {height: '100%', backgroundColor: 'rgba(0,0,0,0.7)'},
  filter: {
    backgroundColor: 'rgba(0,0,0,0)',
    height: '50%',
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  filterBackground: {
    marginTop: 20,
    backgroundColor: '#fff',
    height: '100%',
    borderRadius: 10,
    borderTopColor: '#C7C7CC',
    padding: 20,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterText: {
    fontWeight: '500',
    fontSize: 20,
    color: '#000',
  },
  dropDown: {padding: 20, height: 80},
  inputBorder: {height: 45, backgroundColor: '#fff'},
  dateSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
  },
  filterBtn: {
    width: '90%',
    height: 40,
    backgroundColor: '#00CFE8',
    alignSelf: 'center',
    borderRadius: 10,
  },
  btn: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#fff',
    marginTop: 5,
  },
  borderStyle: {
    width: '49%',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    paddingLeft: 10,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 5,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 3,
  },
  heading: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    left: 10,
    top: -2,
  },
  firstTitle: {fontSize: 12, fontWeight: '600'},
  compulsory: {color: '#EA5455'},
  dropDownMenuFull: {
    borderWidth: 1,
    height: 45,
    marginTop: 15,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
  },
  Input: {flexDirection: 'row', justifyContent: 'space-between'},
  button: {
    height: 45,
    backgroundColor: '#00CFE8',
    borderRadius: 10,
    marginTop: 25,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginTop: 8,
  },
  back: {width: 38, height: 38},
});
