import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {flex: 1, backgroundColor: '#fff', padding: 20},
  header: {flexDirection: 'row', justifyContent: 'space-between'},
  title: {fontSize: 24, fontWeight: '500', color: '#000', marginTop: 0},
  routeBox: {
    width: '100%',
    height: 83,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderWidth: 1,
    backgroundColor: '#ffff',
    shadowColor: '#000',
    elevation: 5,
    marginTop: 13,
    borderRadius: 23,
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  profile: {
    borderRadius: 1000,
    width: 50,
    height: 50,
    marginTop: 5,
    alignSelf: 'center',
  },
  name: {fontSize: 18, fontWeight: '400', color: '#82868B'},
  position: {fontSize: 12, fontWeight: '400', color: '#FF9F43'},
  date: {
    height: 19,
    width: '110%',
    backgroundColor: '#00CFE8',
    position: 'absolute',
    top: 20,
    left: 6,
    borderTopLeftRadius: 11,
    borderBottomLeftRadius: 10,
  },
  dateText: {
    color: '#ffff',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '400',
  },
  Searchbar:{borderColor: '#979797', borderWidth: 0.9, marginTop: 16},
  dropDown:{width:"90%",marginTop:16,alignSelf:"center",},
  topSection: {
    width: '100%',
    height: 120,
    marginTop: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#00CFE8',
    shadowColor: '#000',
    elevation: 2,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    shadowOpacity:0
  
  },
  homeImage: {width: 60, height: 60,alignSelf:"center"},
  storeTitle: {
    fontSize: 18,
    color: '#000',
    fontWeight: '400',
    textAlign: 'left',
  },
  StoreAdd: {fontSize: 14, color: '#979797', fontWeight: '400'},
  storeContact: {flexDirection: 'row', justifyContent: 'space-between'},
  visitDate:{fontSize:12,fontWeight:"400",color:"#00CFE8"},
  visitDay:{fontSize:12,fontWeight:"400",color:"#FF0000"},
  visitNo:{fontSize:40,fontWeight:"400",color:"#00CFE8"},
  visitText:{fontSize:12,fontWeight:"400",color:"#00CFE8",},
  Section:{width: '100%',
  height: 120,
  marginTop: 15,
  borderRadius: 10,
  borderWidth: 1,
  borderColor: '#979797',
  shadowColor: '#000',
  elevation: 2,
  backgroundColor: '#fff',
  flexDirection: 'row',
  justifyContent: 'space-between',
  padding: 20,},
  ConfirmBtn: {
    width: '40%',
    height: 45,
    marginTop: 45,
    alignSelf: 'center',
    backgroundColor: '#00CFE8',
    borderRadius: 5,
  },
  Confirm: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#fff',
    marginTop: 7,
  },
  heading:{flexDirection:"row",justifyContent:"space-between",position:"absolute",left:10,top:-2},
  firstTitle:{fontSize:12,fontWeight:"600"},compulsory:{color:"#EA5455"},
  dropDownMenuFull:{
  
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    borderRadius: 5,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 5,
  },
  borderStyle: {
    width: '100%',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    paddingLeft: 10,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 5,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 3,
  },
  borderStyleSec: {
    width: '100%',
    borderWidth: 1,
    height: 50,
    marginTop: 15,
    borderColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 5,
    backgroundColor: '#fff',
    shadowColor: '#000',
    elevation: 3,
  },
  back:{width:38,height:38}
});
